import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";
import "../app/globals.css";


const geistSans = localFont({
  src: "../app/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../app/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppGuestLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <main className="px-5 mx-auto pt-5">
            <h1 className="text-2xl">Que pasa</h1>
          {children}
        </main>
      </body>
    </html>
  );
}
